spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${KOKO_AUTH_DB_HOST}:${KOKO_AUTH_DB_PORT}/${KOKO_AUTH_DB_NAME}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${KOKO_AUTH_DB_USER}
    password: ${KOKO_AUTH_DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${OAUTH_GOOGLE_CLIENT_ID}
            clientSecret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  app:
    auth:
      tokenSecret: ${APP_AUTH_SECRET}
      tokenExpirationMsec: 864000000
---
spring:
  config:
    activate:
      on-profile: local
  app:
    cors:
      allowedOrigins: http://localhost:3000 # Comma separated list of allowed origins
    oauth2:
      # After successfully authenticating with the OAuth2 Provider,
      # we'll be generating an auth token for the user and sending the token to the
      # redirectUri mentioned by the client in the /oauth2/authorize request.
      # We're not using cookies because they won't work well in mobile clients.
      authorizedRedirectUris:
        - http://localhost:3000/oauth2/redirect
---
spring:
  config:
    activate:
      on-profile: prod
